### ISSUE TITLE
module "generated_kernel_includes": cmd: unknown variable '$(PATH_OVERRIDE_SOONG)'

### ISSUE THREAD

**Issue by ghost** [ProjectSakura/vendor_sakura#12]
What i did:
repo init sakura
cloned device trees (ocean) and motorola vendor
changing files in device trees to work with sakura
brunch ocean_sakura-userdebug (for mka -j6 bacon gives same error)

Info:
I tried building with 2 different folders booth repo init and synced also again manually cloned device trees and build

Error:

┌──(bruno㉿kali)-[/media/bruno/Linux/sakura]
└─$ brunch sakura_ocean-userdebug                                                                                                                                                                                                      
Trying dependencies-only mode on a non-existing device tree?

==========================================================================
* ╭━━━╮╱╱╱╱╱╱╱╱╱╱╱╭╮╱╭━━━╮╱╱╭╮                                            
* ┃╭━╮┃╱╱╱╱╭╮╱╱╱╱╭╯╰╮┃╭━╮┃╱╱┃┃                                            
* ┃╰━╯┣━┳━━╋╋━━┳━┻╮╭╯┃╰━━┳━━┫┃╭┳╮╭┳━┳━━╮                                  
* ┃╭━━┫╭┫╭╮┣┫┃━┫╭━┫┃╱╰━━╮┃╭╮┃╰╯┫┃┃┃╭┫╭╮┃                                  
* ┃┃╱╱┃┃┃╰╯┃┃┃━┫╰━┫╰╮┃╰━╯┃╭╮┃╭╮┫╰╯┃┃┃╭╮┃                                  
* ╰╯╱╱╰╯╰━━┫┣━━┻━━┻━╯╰━━━┻╯╰┻╯╰┻━━┻╯╰╯╰╯                                  
* ╱╱╱╱╱╱╱╱╭╯┃                                                             
* ╱╱╱╱╱╱╱╱╰━╯                                                             
* WELCOME TO PROJECT SAKURA                                               
==========================================================================
SAKURA_VERSION=ProjectSakura-4.R-VANILLA-20210211-1800--UNOFFICIAL
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=11
TARGET_PRODUCT=sakura_ocean
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=generic
BUILD_ID=RQ1A.210205.004
OUT_DIR=out
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.10.0-kali3-amd64-x86_64-Kali-GNU/Linux-Rolling
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
PRODUCT_SOONG_NAMESPACES=vendor/motorola/ocean vendor/motorola/sdm632-common device/motorola/sdm632-common device/motorola/ocean
=========================================================================

18:00:45 ************************************************************
18:00:45 You are building on a machine with 15.6GB of RAM
18:00:45 
18:00:45 The minimum required amount of free memory is around 16GB,
18:00:45 and even with that, some configurations may not work.
18:00:45 
18:00:45 If you run into segfaults or other errors, try reducing your
18:00:45 -j value.
18:00:45 ************************************************************
==========================================================================
* ╭━━━╮╱╱╱╱╱╱╱╱╱╱╱╭╮╱╭━━━╮╱╱╭╮                                            
* ┃╭━╮┃╱╱╱╱╭╮╱╱╱╱╭╯╰╮┃╭━╮┃╱╱┃┃                                            
* ┃╰━╯┣━┳━━╋╋━━┳━┻╮╭╯┃╰━━┳━━┫┃╭┳╮╭┳━┳━━╮                                  
* ┃╭━━┫╭┫╭╮┣┫┃━┫╭━┫┃╱╰━━╮┃╭╮┃╰╯┫┃┃┃╭┫╭╮┃                                  
* ┃┃╱╱┃┃┃╰╯┃┃┃━┫╰━┫╰╮┃╰━╯┃╭╮┃╭╮┫╰╯┃┃┃╭╮┃                                  
* ╰╯╱╱╰╯╰━━┫┣━━┻━━┻━╯╰━━━┻╯╰┻╯╰┻━━┻╯╰╯╰╯                                  
* ╱╱╱╱╱╱╱╱╭╯┃                                                             
* ╱╱╱╱╱╱╱╱╰━╯                                                             
* WELCOME TO PROJECT SAKURA                                               
==========================================================================
SAKURA_VERSION=ProjectSakura-4.R-VANILLA-20210211-1800--UNOFFICIAL
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=11
TARGET_PRODUCT=sakura_ocean
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=generic
BUILD_ID=RQ1A.210205.004
OUT_DIR=out
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.10.0-kali3-amd64-x86_64-Kali-GNU/Linux-Rolling
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
PRODUCT_SOONG_NAMESPACES=vendor/motorola/ocean vendor/motorola/sdm632-common device/motorola/sdm632-common device/motorola/ocean
=========================================================================

[100% 3/3] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: vendor/lineage/build/soong/Android.bp:25:8: module "generated_kernel_includes": cmd: unknown variable '$(PATH_OVERRIDE_SOONG)'
18:01:40 soong bootstrap failed with: exit status 1
module "generated_kernel_includes": cmd: unknown variable 
#### failed to build some targets (55 seconds) ####

**Comment by ghost** [comment]
PS. Sorry for that markdown :'/.

**Comment by LordShenron** [comment]
Hmm.. afaik source is fine.. So this issue is most probably related to your host machine or issue with your kernel. 
Also, we have a separate repository for issues like this so I am closing it.

**Comment by VTVishwanath** [comment]
I am also facing the same issue for RMX1851 while building the ROM. Any solutions @LordShenron  or @ghost ?
